openapi: 3.0.0
info:
  title: Project title
  description: Project description
  version: 0.0.1
tags:
  - name: "example"
    description: "example"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
